import type { CardDefinition } from "@/lib/cards/definitions";
import type { NobleCard } from "@/lib/game/types";

export const nobleDefinitions: CardDefinition<NobleCard>[] = [
  { id: "archbishop", kind: "noble", name: "Archbishop", points: 4, group: "church", quantity: 1 },
  { id: "bad-nun", kind: "noble", name: "Bad Nun", points: 3, group: "church", quantity: 1 },
  { id: "baron", kind: "noble", name: "Baron", points: 3, group: "royal", quantity: 1 },
  { id: "bishop", kind: "noble", name: "Bishop", points: 2, group: "church", quantity: 1 },
  { id: "captain-of-the-guard", kind: "noble", name: "Captain of the Guard", points: 2, group: "military", quantity: 1 },
  { id: "cardinal", kind: "noble", name: "Cardinal", points: 5, group: "church", quantity: 1 },
  { id: "coiffeur", kind: "noble", name: "Coiffeur", points: 1, group: "royal", quantity: 1 },
  { id: "colonel", kind: "noble", name: "Colonel", points: 3, group: "military", quantity: 1 },
  { id: "councilman", kind: "noble", name: "Councilman", points: 3, group: "civic", quantity: 1 },
  { id: "count", kind: "noble", name: "Count", points: 2, group: "royal", quantity: 1 },
  { id: "countess", kind: "noble", name: "Countess", points: 2, group: "royal", quantity: 1 },
  { id: "duke", kind: "noble", name: "Duke", points: 3, group: "royal", quantity: 1 },
  { id: "fast-noble", kind: "noble", name: "Fast Noble", points: 2, group: "royal", quantity: 1 },
  { id: "general", kind: "noble", name: "General", points: 4, group: "military", quantity: 1 },
  { id: "governor", kind: "noble", name: "Governor", points: 4, group: "civic", quantity: 1 },
  { id: "heretic", kind: "noble", name: "Heretic", points: 2, group: "church", quantity: 1 },
  { id: "hero-of-the-people", kind: "noble", name: "Hero of the People", points: -3, group: "gray", quantity: 1 },
  { id: "innocent-victim", kind: "noble", name: "Innocent Victim", points: -1, group: "gray", quantity: 1 },
  { id: "king-louis-xvi", kind: "noble", name: "King Louis XVI", points: 5, group: "royal", quantity: 1 },
  { id: "lady", kind: "noble", name: "Lady", points: 2, group: "royal", quantity: 1 },
  { id: "lady-in-waiting", kind: "noble", name: "Lady in Waiting", points: 1, group: "royal", quantity: 1 },
  { id: "land-lord", kind: "noble", name: "Land Lord", points: 2, group: "civic", quantity: 1 },
  { id: "lieutenant", kind: "noble", name: "Lieutenant", points: 2, group: "military", quantity: 2 },
  { id: "lord", kind: "noble", name: "Lord", points: 2, group: "royal", quantity: 1 },
  { id: "marie-antoinette", kind: "noble", name: "Marie Antoinette", points: 5, group: "royal", quantity: 1 },
  { id: "martyr", kind: "noble", name: "Martyr", points: -1, group: "gray", quantity: 3 },
  { id: "master-spy", kind: "noble", name: "Master Spy", points: 4, group: "military", quantity: 1 },
  { id: "mayor", kind: "noble", name: "Mayor", points: 3, group: "civic", quantity: 1 },
  {
    id: "palace-guard",
    kind: "noble",
    name: "Palace Guard",
    points: 1,
    group: "military",
    quantity: 5,
    description: "Special scoring later: each Palace Guard is worth the number of Palace Guards in that player's score pile.",
  },
  { id: "piss-boy", kind: "noble", name: "Piss Boy", points: 1, group: "royal", quantity: 1 },
  { id: "regent", kind: "noble", name: "Regent", points: 4, group: "royal", quantity: 1 },
  { id: "rival-executioner", kind: "noble", name: "Rival Executioner", points: 1, group: "civic", quantity: 1 },
  { id: "robespierre", kind: "noble", name: "Robespierre", points: 3, group: "royal", quantity: 1 },
  { id: "royal-cartographer", kind: "noble", name: "Royal Cartographer", points: 1, group: "royal", quantity: 1 },
  { id: "sheriff", kind: "noble", name: "Sheriff", points: 1, group: "civic", quantity: 2 },
  { id: "tax-collector", kind: "noble", name: "Tax Collector", points: 2, group: "civic", quantity: 1 },
  { id: "the-clown", kind: "noble", name: "The Clown", points: -2, group: "gray", quantity: 1 },
  {
    id: "tragic-figure",
    kind: "noble",
    name: "Tragic Figure",
    points: -1,
    group: "gray",
    quantity: 1,
    description: "Special scoring later: worth -1 for each gray noble in that player's score pile.",
  },
  { id: "unpopular-judge", kind: "noble", name: "Unpopular Judge", points: 2, group: "civic", quantity: 2 },
  { id: "wealthy-priest", kind: "noble", name: "Wealthy Priest", points: 1, group: "church", quantity: 2 },
];

export const NOBLE_DECK_SIZE = 50;
